### ISSUE TITLE
Add support for 3D Volumetric Cloud

### ISSUE THREAD

**Issue by sairam4123** [clayjohn/godot-volumetric-cloud-demo#1]
Hi. Could you add support for 3D Volumetric Cloud like in Microsoft Flight Simulator, but with the option to reduce the quality?
Let me know if you could. 
Thanks in advance!

**Comment by clayjohn** [comment]
Hi, Thank you for your interest in this demo. 

I have no plans to add new features to this demo. I have purposefully kept the code as simple as possible so that it can be used as an educational tool rather than optimize it to be used as a feature in real games.

**Comment by sairam4123** [comment]
Alright then, thanks for your response!
